### ISSUE TITLE
Adding I2C and UART Patch

### ISSUE THREAD

**Issue by Sona-Subair** [cu-ecen-aeld/final-project-PeterBraganza#10]
DOD:
 * I2C and UART folders for patches are added in buildroot and buildroot config is changed accordingly

**Comment by Sona-Subair** [comment]
https://github.com/cu-ecen-aeld/final-project-Sona-Subair/tree/main/base_external/patches/linux

**Comment by Sona-Subair** [comment]
https://github.com/cu-ecen-aeld/final-project-Sona-Subair/tree/main/base_external/patches/linux

Commit hash: https://github.com/cu-ecen-aeld/final-project-Sona-Subair/commit/4bcd034b89965c67a9c1cac788e0e8799c71ca86

**Comment by Sona-Subair** [comment]
Follow up:
[Verification](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/11)

**Comment by dwalkes** [comment]
@Sona-Subair see discussion in class today - I don't think these will work on beaglebone.

**Comment by Sona-Subair** [comment]
@dwalkes We are working on Buildroot 2019.05 version, we saw the verification results on the hardware support link.  We planned to do the verification this week  due to inconsistency in the buildroot image back then. Please see the link here https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/11.
