### ISSUE TITLE
I2C and UART sensor integration

### ISSUE THREAD

**Issue by PeterBraganza** [cu-ecen-aeld/final-project-PeterBraganza#12]
Application code which reads both I2C and UART sensor data and sends it over socket application

DoD:
 * Able to get both sensor data. 
 * Able to send it over LAN(socket connection) and see same data values on client side

Blockers:
* [I2C Application code ](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/4)
* [Socket code ](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/6)

**Comment by suryakanteti** [comment]
Added function in the GPS module to populate a string with the required data at repo https://github.com/cu-ecen-aeld/final-project-suryakanteti, commit ID 5134368238371359144fe7ca716214e265e9d9ee.

**Comment by suryakanteti** [comment]
Updated the application code to include this function and checked the string. Seems to be working.

**Comment by suryakanteti** [comment]
Changed the function signatures in GPS application layer for ease of access with the socket code.

Repo: https://github.com/cu-ecen-aeld/final-project-suryakanteti
Commit ID: 4f93a1807bf1f7920172a1a7b8ad32fe989acb1f

**Comment by suryakanteti** [comment]
Integrated on the server side and tested on the beaglebone. Seems to be sending the messages correctly. Since it was tested in the ESE lab, the GPS values were empty.

Commit ID: 2704ba736784e94b239bc7ee8a102daffb209280

**Comment by suryakanteti** [comment]
The current commit (74f30d6387a4e720adcaa67207602b7a40de6f92) is working. Need to send only the bytes in one message on server side to avoid filling the buffer frequently.

**Comment by suryakanteti** [comment]
Integration done. Need to test it out on two different beaglebone boards.

**Comment by suryakanteti** [comment]
Tested on two different beaglebone boards and used the home router for this. Able to see the sensor data sent from server to the client, where the client prints it on the console.
