### ISSUE TITLE
UART application layer code

### ISSUE THREAD

**Issue by PeterBraganza** [cu-ecen-aeld/final-project-PeterBraganza#4]
Write an application layer for the GPS module. This application layer will be used with sample driver code and later will be used for the UART device driver.

DoD: 
*  Able to read GPS co-ordinates on the terminal.

Blocker:
* [Buildroot image deployment check](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/9)

**Comment by suryakanteti** [comment]
New blockers from current sprint:
* [Verify UART and I2C patches](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/11)
* [UART Sample Driver](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/1)

**Comment by suryakanteti** [comment]
Initially wrote logic to read multiple bytes of data (256) from the sensor. Turns out the UART driver we used, only gives 1 byte of data per read.

Modified the application logic to read 1 byte at a time until the end of one message ('\n').

**Comment by suryakanteti** [comment]
The information needed from the GPS sensor is:
1. Latitude
2. Latitude direction
3. Longitude
4. Longitude direction
5. UTC time

There are multiple messages from the GPS sensor, but the one that gives us the needed information is **GPGLL**. The current code (https://github.com/cu-ecen-aeld/final-project-suryakanteti/tree/main/gps_application_code, commit ID e9c8638d68596fa8f30e46301c9463dadaa3a748) parses the GPS data for this message and stores it in a structure, prints it on the console.

The code is structured in a way that it can be used to extend to include the other message as well (GPGGA, GPGSA etc.)

**Comment by suryakanteti** [comment]
Tested the built user-space application on the beaglebone board.

![20221203_175626](https://user-images.githubusercontent.com/81984166/205476629-9c2ab5d8-173c-46a1-989c-c130542140f4.jpg)

**Comment by suryakanteti** [comment]
The UTC was earlier not as expected due to a parsing issue. Checked in the correction at commit ID afcbb9b5f82c5f2c003bf6e86d4ec37e1021380d.

**Comment by suryakanteti** [comment]
Correction working and checked on beaglebone board. Application layer for GPS done.
