### ISSUE TITLE
Socket code implementation

### ISSUE THREAD

**Issue by PeterBraganza** [cu-ecen-aeld/final-project-PeterBraganza#6]

**Comment by suryakanteti** [comment]
DoD:

Client Socket communication pair of applications where the message sent from one beaglebone board (client) end can be seen on another beaglebone board (server).

Blockers:

* [Buildroot image deployment check](https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/9) can be a blocker while trying to test on beaglebone boards.

Alternative approach / Fallback plan:
* Check the socket logic on two regular linux machines and test it on beaglebone boards once Issue https://github.com/cu-ecen-aeld/final-project-PeterBraganza/issues/9 is resolved.

**Comment by Sona-Subair** [comment]
Deployed and verified socket communication. The code can be found under these final commit hashes:
[#1](https://github.com/cu-ecen-aeld/final-project-suryakanteti/commit/bc5df9fbc084c791687cf51d0051e7f6c58e3bd3)
[#2](https://github.com/cu-ecen-aeld/final-project-Sona-Subair/commit/d121775a661b94bee302ba6df8ed104ed710a0cb)
Screenshot of the captured is given below:
![Screenshot_from_2022-12-04_17-53-46](https://user-images.githubusercontent.com/90170878/205529798-bc356977-9422-4927-a6ed-10ac4ede3995.png)
